token = "your_token_here"
ignorePrefix = "!!"

[twitter]
download = false
embed_provider = "fxtwitter.com"

[reddit]
download = false
embed_provider = "rxddit.com"

[tiktok]
download = false
embed_provider = "tnktok.com"
